Controllers/ContratoController.cs
using Microsoft.AspNetCore.Mvc;
using Inmobiliaria.Models;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace Inmobiliaria.Controllers;

public class ContratoController : Controller
{
    private readonly ILogger<ContratoController> _logger;

    private ContratoRepository repository;
    private InmuebleRepository inmuebleRrepository;
    private InquilinoRepository inquilinoRrepository;
    private PropietarioRepository propietarioRepository;
    public ContratoController(ILogger<ContratoController> logger)
    {
        _logger = logger;
        repository = new ContratoRepository();
        inmuebleRrepository = new InmuebleRepository();
        inquilinoRrepository = new InquilinoRepository();
        propietarioRepository = new PropietarioRepository();
    }

    public IActionResult Index()
    {
        var contratos = repository.GetAll();
        return View(contratos);
    }

    public IActionResult Create()
    {
        var inmuebles = inmuebleRrepository.GetAll();
        ViewBag.Inmuebles = new SelectList(inmuebles, "Id", "Direccion");
        var inquilinos = inquilinoRrepository.GetAll();
        ViewBag.Inquilinos = new SelectList(inquilinos, "Id", "Nombre");
        return View();
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    public IActionResult Create(Contrato contrato)
    {
        repository.InsertContrato(contrato);
        return RedirectToAction(nameof(Index));
    }

    public IActionResult Edit(int id)
    {
        var inmuebles = inmuebleRrepository.GetAll();
        ViewBag.Inmuebles = new SelectList(inmuebles, "Id", "Direccion");
        var inquilinos = inquilinoRrepository.GetAll();
        ViewBag.Inquilinos = new SelectList(inquilinos, "Id", "Dni");
        if (id == 0) return View();
        var contrato = repository.GetContratoById(id);
        return View(contrato);
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    public IActionResult Edit(Contrato contrato)
    {
        repository.EditContrato(contrato);
        return RedirectToAction(nameof(Index));
    }

    public IActionResult Details(int id)
    {
        var contrato = repository.GetContratoById(id);
        var inmueble = inmuebleRrepository.GetInmuebleById(contrato.Contrato_inmueble);
        ViewBag.Inmueble = inmueble;
        var inquilino = inquilinoRrepository.GetInquilinoById(contrato.Contrato_inquilino);
        ViewBag.Inquilino = inquilino;
        var propietario = propietarioRepository.GetPropietarioById(inmueble.Inmueble_propietario);
        ViewBag.Propietario = propietario;
        return View(contrato);
    }
    public IActionResult Delete(int id)
    {
        var contrato = repository.GetContratoById(id);
        return View(contrato);
    }

    [HttpPost]
    public IActionResult DeleteConfirmed(int id)
    {
        repository.DeleteContrato(id);
        return RedirectToAction(nameof(Index));
    }
}

Controllers/InmuebleController.cs
using Microsoft.AspNetCore.Mvc;
using Inmobiliaria.Models;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace Inmobiliaria.Controllers;

public class InmuebleController : Controller
{
    private readonly ILogger<InmuebleController> _logger;
    private InmuebleRepository repository;
    private PropietarioRepository propietarioRepository;
    public InmuebleController(ILogger<InmuebleController> logger)
    {
        _logger = logger;
        repository = new InmuebleRepository();
        propietarioRepository = new PropietarioRepository();
    }

    public IActionResult Index()
    {
        var inmuebles = repository.GetAll();
        return View(inmuebles);
    }

    public IActionResult Create()
    {
        var propietarios = propietarioRepository.GetAll();
        ViewBag.Propietarios = new SelectList(propietarios, "Id", "Nombre");
        return View();
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    public IActionResult Create(Inmueble inmueble)
    {
        repository.InsertInmueble(inmueble);
        return RedirectToAction(nameof(Index));
    }

    public IActionResult Edit(int id)
    {
        if (id == 0) return View();
        var inmueble = repository.GetInmuebleById(id);
        var propietarios = propietarioRepository.GetAll();
        ViewBag.Propietarios = new SelectList(propietarios, "Id", "Nombre");
        return View(inmueble);
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    public IActionResult Edit(Inmueble inmueble)
    {
        repository.EditInmueble(inmueble);
        return RedirectToAction(nameof(Index));
    }

    public IActionResult Details(int id)
    {
        var inmueble = repository.GetInmuebleById(id);
        var propietario = propietarioRepository.GetPropietarioById(inmueble.Inmueble_propietario);
        ViewBag.Propietario = propietario;
        return View(inmueble);
    }
    public IActionResult Delete(int id)
    {
        var inmueble = repository.GetInmuebleById(id);
        return View(inmueble);
    }

    [HttpPost]
    public IActionResult DeleteConfirmed(int id)
    {
        repository.DeleteInmueble(id);
        return RedirectToAction(nameof(Index));
    }
}

Controllers/InquilinoController.cs
using Microsoft.AspNetCore.Mvc;
using Inmobiliaria.Models;

namespace Inmobiliaria.Controllers;

public class InquilinoController : Controller
{
    private readonly ILogger<InquilinoController> _logger;
    private InquilinoRepository repository;
    public InquilinoController(ILogger<InquilinoController> logger)
    {
        _logger = logger;
        repository = new InquilinoRepository();
    }

    public IActionResult Index()
    {
        var inquilinos = repository.GetAll();
        return View(inquilinos);
    }

    public IActionResult Create()
    {
        return View();
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    public IActionResult Create(Inquilino inquilino)
    {
        repository.InsertInquilino(inquilino);
        return RedirectToAction(nameof(Index));
    }

    public IActionResult Edit(int id)
    {
        if (id == 0) return View();
        var inquilino = repository.GetInquilinoById(id);
        return View(inquilino);
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    public IActionResult Edit(Inquilino inquilino)
    {
        repository.EditInquilino(inquilino);
        return RedirectToAction(nameof(Index));
    }

    public IActionResult Details(int id)
    {
        var inquilino = repository.GetInquilinoById(id);
        return View(inquilino);
    }
    public IActionResult Delete(int id)
    {
        var inquilino = repository.GetInquilinoById(id);
        return View(inquilino);
    }

    [HttpPost]
    public IActionResult DeleteConfirmed(int id)
    {
        repository.DeleteInquilino(id);
        return RedirectToAction(nameof(Index));
    }
}

Controllers/PropietarioController.cs
using Microsoft.AspNetCore.Mvc;
using Inmobiliaria.Models;

namespace Inmobiliaria.Controllers;

public class PropietarioController : Controller
{
    private readonly ILogger<PropietarioController> _logger;
    private PropietarioRepository repository;
    public PropietarioController(ILogger<PropietarioController> logger)
    {
        _logger = logger;
        repository = new PropietarioRepository();
    }

    public IActionResult Index()
    {
        var propietarios = repository.GetAll();
        return View(propietarios);
    }

    public IActionResult Create()
    {
        return View();
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    public IActionResult Create(Propietario propietario)
    {
        repository.InsertPropietario(propietario);
        return RedirectToAction(nameof(Index));
    }

    public IActionResult Edit(int id)
    {
        if (id == 0) return View();
        var propietario = repository.GetPropietarioById(id);
        return View(propietario);
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    public IActionResult Edit(Propietario propietario)
    {
        repository.EditPropietario(propietario);
        return RedirectToAction(nameof(Index));
    }

    public IActionResult Details(int id)
    {
        var propietario = repository.GetPropietarioById(id);
        return View(propietario);
    }
    public IActionResult Delete(int id)
    {
        var propietario = repository.GetPropietarioById(id);
        return View(propietario);
    }

    [HttpPost]
    public IActionResult DeleteConfirmed(int id)
    {
        repository.DeletePropietario(id);
        return RedirectToAction(nameof(Index));
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Inmobiliaria</title>
    <script type="importmap"></script>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Inmobiliaria.styles.css" asp-append-version="true" />
</head>

<body>
    <header>
        <nav
            class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-danger-subtle border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Inmobiliaria</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse"
                    aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav">
                        <li class="nav-item">
                            <a class="nav-link" asp-controller="Propietario" asp-action="Index">Propietarios</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-controller="Inquilino" asp-action="Index">Inquilinos</a>
                        </li>
                        <li class="nav-item"></li>
                        <a class="nav-link" asp-controller="Inmueble" asp-action="Index">Inmuebles</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-controller="Contrato" asp-action="Index">Contratos</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted bg-danger-subtle">
        <div class="container">
            &copy; 2025 - Inmobiliaria - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>

</html>